plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Project: automated_pipeline
  tag:Environment: dev
  instance-state-name: running
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address